## Email (SMTP) configuration for order confirmation
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=travellingislife04@gmail.com
spring.mail.password=cgqqxzosejvwjfpw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=harpreet.saggu
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
## PayPal API credentials
paypal.client.id=ARWeIkgt5CCPWsM0g1eq4w6Tulgg581hSgUbIlqD2qrQqQBeZ2L6zr1vXc0VFmYEZs94XSNNfCC6v4n_
paypal.client.secret=EARQuk5E821Xqz09IcWi0DEt5JeP-1CYlbsN0baZeEe6UKetQGJvLrJCTBIpmF9xNcP78MWgw4lfJiZG
paypal.mode=sandbox