name: CI/CD Pipeline

on:
  push:
    branches: [ main, story/ECommerce/GithubActionsSetup ]
  pull_request:
    branches: [ main, story/ECommerce/GithubActionsSetup ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ecommerce_db
          POSTGRES_USER: harpreet.saggu
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U harpreet.saggu -d ecommerce_db" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend with Maven (skip tests)
        working-directory: backend
        run: ./mvnw clean install -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install


  deploy-backend:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend with Maven (skip tests)
        working-directory: backend
        run: ./mvnw clean package -DskipTests

      - name: Generate deployment package (ZIP)
        run: zip -r backend-deploy.zip backend/target/*.jar backend/.ebextensions || zip -r backend-deploy.zip backend/target/*.jar

      - name: Debug secrets
        run: |
          echo "Key present: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "Secret present: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"
      


      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: ecommerce-backend
          environment_name: ecommerce-backend-env
          version_label: github-${{ github.run_number }}
          region: eu-north-1
          deployment_package: backend-deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
